<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BookingGymTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booking_gym')->delete();
        
        \DB::table('booking_gym')->insert(array (
            0 => 
            array (
                'no_booking' => 1,
                'tanggal_booking' => '2023-03-02',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.001',
                'no_struk' => '23.06.013',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'no_booking' => 2,
                'tanggal_booking' => '2023-03-02',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.002',
                'no_struk' => '23.06.014',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'no_booking' => 3,
                'tanggal_booking' => '2023-03-02',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.003',
                'no_struk' => '23.06.015',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'no_booking' => 4,
                'tanggal_booking' => '2023-03-03',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.004',
                'no_struk' => '23.06.260',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-05-19 08:10:28',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'no_booking' => 5,
                'tanggal_booking' => '2023-03-03',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.005',
                'no_struk' => '23.06.265',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-05-19 08:29:58',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'no_booking' => 6,
                'tanggal_booking' => '2023-03-04',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-05',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.006',
                'no_struk' => '23.06.016',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'no_booking' => 7,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.001',
                'no_struk' => '23.06.017',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'no_booking' => 8,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.002',
                'no_struk' => '23.06.018',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'no_booking' => 9,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.003',
                'no_struk' => '23.06.019',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-04-02 00:54:36',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'no_booking' => 10,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.004',
                'no_struk' => NULL,
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-05-19 08:46:17',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'no_booking' => 11,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.037',
                'no_struk' => NULL,
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-05-19 08:47:34',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'no_booking' => 12,
                'tanggal_booking' => '2023-03-05',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-03-10',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.037',
                'no_struk' => '23.06.279',
                'created_at' => '2023-04-02 00:54:36',
                'updated_at' => '2023-05-19 09:02:11',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'no_booking' => 16,
                'tanggal_booking' => '2023-05-16',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-18',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-17 15:49:39',
                'updated_at' => '2023-05-19 07:12:31',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'no_booking' => 28,
                'tanggal_booking' => '2023-05-17',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-19',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.037',
                'no_struk' => '23.06.280',
                'created_at' => '2023-05-17 21:27:30',
                'updated_at' => '2023-05-19 09:03:18',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'no_booking' => 32,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.036',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:32',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'no_booking' => 33,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.036',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'no_booking' => 34,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => '23.06.311',
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => '2023-05-20 15:56:09',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'no_booking' => 35,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'no_booking' => 36,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'no_booking' => 37,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'no_booking' => 38,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'no_booking' => 39,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:58',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'no_booking' => 40,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 1,
                'waktu_presensi' => '2023-06-07 21:05:34',
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:59',
                'updated_at' => '2023-06-07 21:05:34',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'no_booking' => 41,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-25',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.033',
                'no_struk' => NULL,
                'created_at' => '2023-05-19 14:16:59',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'no_booking' => 45,
                'tanggal_booking' => '2023-05-19',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-30',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 1,
                'id_member' => '23.06.034',
                'no_struk' => '23.06.309',
                'created_at' => '2023-05-19 14:32:48',
                'updated_at' => '2023-05-19 14:33:51',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'no_booking' => 46,
                'tanggal_booking' => '2023-05-20',
                'is_canceled' => 1,
                'tanggal_sesi_gym' => '2023-05-23',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 7,
                'id_member' => '23.06.034',
                'no_struk' => NULL,
                'created_at' => '2023-05-20 18:20:39',
                'updated_at' => '2023-05-20 18:20:56',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'no_booking' => 47,
                'tanggal_booking' => '2023-05-23',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-24',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 4,
                'id_member' => '23.06.034',
                'no_struk' => NULL,
                'created_at' => '2023-05-23 15:52:39',
                'updated_at' => '2023-05-23 15:52:39',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'no_booking' => 48,
                'tanggal_booking' => '2023-05-24',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-21',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.036',
                'no_struk' => NULL,
                'created_at' => '2023-05-24 08:16:06',
                'updated_at' => '2023-05-24 08:16:06',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'no_booking' => 49,
                'tanggal_booking' => '2023-05-25',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-27',
                'status_kehadiran' => 1,
                'waktu_presensi' => NULL,
                'id_sesi' => 2,
                'id_member' => '23.06.036',
                'no_struk' => NULL,
                'created_at' => '2023-05-25 22:21:16',
                'updated_at' => '2023-05-25 22:21:16',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'no_booking' => 50,
                'tanggal_booking' => '2023-05-26',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-27',
                'status_kehadiran' => 1,
                'waktu_presensi' => '2023-06-07 21:10:34',
                'id_sesi' => 3,
                'id_member' => '23.06.034',
                'no_struk' => NULL,
                'created_at' => '2023-05-26 13:07:12',
                'updated_at' => '2023-05-26 13:07:12',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'no_booking' => 51,
                'tanggal_booking' => '2023-05-26',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-31',
                'status_kehadiran' => 0,
                'waktu_presensi' => '2023-06-07 00:00:00',
                'id_sesi' => 3,
                'id_member' => '23.06.034',
                'no_struk' => NULL,
                'created_at' => '2023-05-26 13:09:44',
                'updated_at' => '2023-05-26 13:09:44',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'no_booking' => 52,
                'tanggal_booking' => '2023-05-28',
                'is_canceled' => 0,
                'tanggal_sesi_gym' => '2023-05-30',
                'status_kehadiran' => 0,
                'waktu_presensi' => NULL,
                'id_sesi' => 3,
                'id_member' => '23.06.036',
                'no_struk' => NULL,
                'created_at' => '2023-05-28 19:02:46',
                'updated_at' => '2023-05-28 19:02:46',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}