<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PenggunaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pengguna')->delete();
        
        \DB::table('pengguna')->insert(array (
            0 => 
            array (
                'id_pengguna' => 1,
                'username' => 'alfonsus',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-28 13:55:35',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id_pengguna' => 2,
                'username' => 'ucup_surucup',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-06-05 18:14:38',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id_pengguna' => 3,
                'username' => 'udin_saprudin',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-21 17:09:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id_pengguna' => 4,
                'username' => 'faizah_nugraha',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id_pengguna' => 5,
                'username' => 'nadya',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id_pengguna' => 6,
                'username' => 'henry',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id_pengguna' => 7,
                'username' => 'Alfonsus',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id_pengguna' => 8,
                'username' => 'JK',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id_pengguna' => 9,
                'username' => 'Lisa',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id_pengguna' => 10,
                'username' => 'Hobby',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id_pengguna' => 11,
                'username' => 'V',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id_pengguna' => 12,
                'username' => 'Jenny',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id_pengguna' => 13,
                'username' => 'Suga',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id_pengguna' => 14,
                'username' => 'Jin',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id_pengguna' => 15,
                'username' => 'Jiso',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-05-16 01:18:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id_pengguna' => 16,
                'username' => 'Jimin',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id_pengguna' => 17,
                'username' => 'Rose',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id_pengguna' => 18,
                'username' => 'Jessi',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id_pengguna' => 19,
                'username' => 'admin',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id_pengguna' => 20,
                'username' => 'admin_ganteng1',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id_pengguna' => 21,
                'username' => 'mo_ganteng1',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-05-16 01:14:11',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id_pengguna' => 22,
                'username' => 'Yunita',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id_pengguna' => 23,
                'username' => 'Putri',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id_pengguna' => 24,
                'username' => 'Yuna',
                'password' => bcrypt('0541'),
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id_pengguna' => 25,
                'username' => 'Bambang',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id_pengguna' => 26,
                'username' => 'Tono',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id_pengguna' => 27,
                'username' => 'Adi',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id_pengguna' => 28,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:38:53',
                'updated_at' => '2023-04-14 20:38:53',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id_pengguna' => 29,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:39:32',
                'updated_at' => '2023-04-14 20:39:32',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id_pengguna' => 30,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:45:15',
                'updated_at' => '2023-04-14 20:45:15',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id_pengguna' => 31,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:52:12',
                'updated_at' => '2023-04-14 20:52:12',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id_pengguna' => 32,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:52:55',
                'updated_at' => '2023-04-14 20:52:55',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id_pengguna' => 33,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:53:35',
                'updated_at' => '2023-04-14 20:53:35',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id_pengguna' => 34,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:54:28',
                'updated_at' => '2023-04-14 20:54:28',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id_pengguna' => 35,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:54:46',
                'updated_at' => '2023-04-14 20:54:46',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id_pengguna' => 36,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:55:10',
                'updated_at' => '2023-04-14 20:55:10',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id_pengguna' => 37,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:55:40',
                'updated_at' => '2023-04-14 20:55:40',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id_pengguna' => 38,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:01:58',
                'updated_at' => '2023-04-14 21:01:58',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id_pengguna' => 39,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:03:13',
                'updated_at' => '2023-04-14 21:03:13',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id_pengguna' => 40,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:06:27',
                'updated_at' => '2023-04-14 21:06:27',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id_pengguna' => 41,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:14:55',
                'updated_at' => '2023-04-14 21:14:55',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id_pengguna' => 42,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:15:32',
                'updated_at' => '2023-04-14 21:15:32',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id_pengguna' => 43,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:16:27',
                'updated_at' => '2023-04-14 21:16:27',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id_pengguna' => 44,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:18:00',
                'updated_at' => '2023-04-14 21:18:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id_pengguna' => 45,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:19:37',
                'updated_at' => '2023-04-14 21:19:37',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id_pengguna' => 46,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:20:55',
                'updated_at' => '2023-04-14 21:20:55',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id_pengguna' => 47,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:23:16',
                'updated_at' => '2023-04-14 21:23:16',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id_pengguna' => 48,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:25:07',
                'updated_at' => '2023-04-14 21:25:07',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id_pengguna' => 49,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:25:44',
                'updated_at' => '2023-04-14 21:25:44',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id_pengguna' => 50,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:27:54',
                'updated_at' => '2023-04-14 21:27:54',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id_pengguna' => 51,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:28:10',
                'updated_at' => '2023-04-14 21:28:10',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id_pengguna' => 52,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:28:59',
                'updated_at' => '2023-04-14 21:28:59',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id_pengguna' => 53,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:30:03',
                'updated_at' => '2023-04-14 21:30:03',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id_pengguna' => 54,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:32:35',
                'updated_at' => '2023-04-14 21:32:35',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id_pengguna' => 55,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:32:47',
                'updated_at' => '2023-04-14 21:32:47',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id_pengguna' => 56,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:56:10',
                'updated_at' => '2023-04-14 21:56:10',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id_pengguna' => 57,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:12:22',
                'updated_at' => '2023-04-14 22:12:22',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id_pengguna' => 58,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:16:46',
                'updated_at' => '2023-04-14 22:16:46',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id_pengguna' => 59,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:16:59',
                'updated_at' => '2023-04-14 22:16:59',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id_pengguna' => 60,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:17:27',
                'updated_at' => '2023-04-14 22:17:27',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id_pengguna' => 61,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:40:31',
                'updated_at' => '2023-04-14 22:40:31',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id_pengguna' => 62,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:52:33',
                'updated_at' => '2023-04-14 22:52:33',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id_pengguna' => 63,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:53:48',
                'updated_at' => '2023-04-14 22:53:48',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id_pengguna' => 64,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:53:59',
                'updated_at' => '2023-04-14 22:53:59',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id_pengguna' => 65,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:56:17',
                'updated_at' => '2023-04-14 22:56:17',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id_pengguna' => 66,
                'username' => 'alfons',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:57:47',
                'updated_at' => '2023-04-14 22:57:47',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id_pengguna' => 67,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:31:07',
                'updated_at' => '2023-04-15 08:31:07',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id_pengguna' => 70,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:32:44',
                'updated_at' => '2023-04-15 08:32:44',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id_pengguna' => 73,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:35:31',
                'updated_at' => '2023-04-15 08:35:31',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id_pengguna' => 74,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:35:54',
                'updated_at' => '2023-04-30 19:06:55',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id_pengguna' => 75,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:37:18',
                'updated_at' => '2023-04-15 08:37:18',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id_pengguna' => 76,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:37:36',
                'updated_at' => '2023-04-15 08:37:36',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id_pengguna' => 91,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:50:36',
                'updated_at' => '2023-04-15 08:50:36',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id_pengguna' => 92,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:51:45',
                'updated_at' => '2023-04-15 08:51:45',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id_pengguna' => 93,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:52:35',
                'updated_at' => '2023-04-15 08:52:35',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id_pengguna' => 94,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:52:54',
                'updated_at' => '2023-04-15 08:52:54',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id_pengguna' => 97,
                'username' => '23.04.040',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:55:39',
                'updated_at' => '2023-04-15 08:55:39',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id_pengguna' => 98,
                'username' => '23.04.041',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:56:24',
                'updated_at' => '2023-04-15 08:56:24',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id_pengguna' => 99,
                'username' => '23.04.021',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:03:56',
                'updated_at' => '2023-05-03 13:37:02',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id_pengguna' => 101,
                'username' => '23.04.023',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:35:25',
                'updated_at' => '2023-04-21 00:35:25',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id_pengguna' => 102,
                'username' => '23.04.024',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:39:12',
                'updated_at' => '2023-04-21 00:39:12',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id_pengguna' => 103,
                'username' => '23.04.025',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:51:59',
                'updated_at' => '2023-04-21 00:51:59',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id_pengguna' => 104,
                'username' => '23.04.026',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:52:09',
                'updated_at' => '2023-04-21 00:52:09',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id_pengguna' => 105,
                'username' => '23.04.027',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:52:19',
                'updated_at' => '2023-04-21 00:52:19',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id_pengguna' => 106,
                'username' => '23.04.028',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:53:05',
                'updated_at' => '2023-04-21 00:53:05',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id_pengguna' => 107,
                'username' => '23.04.029',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:59:36',
                'updated_at' => '2023-04-21 00:59:36',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id_pengguna' => 109,
                'username' => '23.04.031',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 01:08:35',
                'updated_at' => '2023-04-21 01:08:35',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id_pengguna' => 110,
                'username' => '23.04.032',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 01:08:42',
                'updated_at' => '2023-04-21 01:08:42',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id_pengguna' => 111,
                'username' => '23.04.033',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 15:00:57',
                'updated_at' => '2023-04-21 15:00:57',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id_pengguna' => 113,
                'username' => '23.04.035',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 15:01:49',
                'updated_at' => '2023-04-21 15:01:49',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id_pengguna' => 118,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:23:21',
                'updated_at' => '2023-04-26 10:23:21',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id_pengguna' => 119,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:25:16',
                'updated_at' => '2023-04-26 10:25:16',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id_pengguna' => 120,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:26',
                'updated_at' => '2023-04-26 10:26:26',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id_pengguna' => 121,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:47',
                'updated_at' => '2023-04-26 10:26:47',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id_pengguna' => 122,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:48',
                'updated_at' => '2023-04-26 10:26:48',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id_pengguna' => 123,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:19',
                'updated_at' => '2023-04-26 10:27:19',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id_pengguna' => 124,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:20',
                'updated_at' => '2023-04-26 10:27:20',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id_pengguna' => 125,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:23',
                'updated_at' => '2023-04-26 10:27:23',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id_pengguna' => 130,
                'username' => '23.04.036',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 10:44:58',
                'updated_at' => '2023-04-28 10:44:58',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id_pengguna' => 131,
                'username' => '23.04.037',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 10:45:04',
                'updated_at' => '2023-05-03 13:34:13',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id_pengguna' => 138,
                'username' => 'Lisa Blacpink',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 13:46:06',
                'updated_at' => '2023-04-28 13:46:06',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id_pengguna' => 139,
                'username' => '23.04.038',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 13:50:17',
                'updated_at' => '2023-04-28 13:50:17',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id_pengguna' => 140,
                'username' => 'Jamet',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-29 21:36:55',
                'updated_at' => '2023-04-29 21:36:55',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id_pengguna' => 141,
                'username' => '23.04.039',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-30 19:02:55',
                'updated_at' => '2023-04-30 19:02:55',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id_pengguna' => 143,
                'username' => '23.05.040',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-05 13:32:38',
                'updated_at' => '2023-05-05 13:32:38',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id_pengguna' => 144,
                'username' => '23.05.041',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:02:22',
                'updated_at' => '2023-05-11 03:03:08',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id_pengguna' => 146,
                'username' => '23.05.042',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:09:32',
                'updated_at' => '2023-05-11 03:09:32',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id_pengguna' => 147,
                'username' => '23.05.043',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:13:59',
                'updated_at' => '2023-05-11 03:13:59',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id_pengguna' => 148,
                'username' => '-',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:15:16',
                'updated_at' => '2023-05-11 03:15:16',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id_pengguna' => 149,
                'username' => '23.05.044',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:15:59',
                'updated_at' => '2023-05-16 01:16:16',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id_pengguna' => 151,
                'username' => '23.05.045',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:21:51',
                'updated_at' => '2023-05-24 07:21:51',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id_pengguna' => 152,
                'username' => '23.05.045',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:23:14',
                'updated_at' => '2023-05-24 07:23:14',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id_pengguna' => 154,
                'username' => '23.05.047',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:25:38',
                'updated_at' => '2023-05-24 07:25:38',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id_pengguna' => 155,
                'username' => '23.05.048',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:26:44',
                'updated_at' => '2023-05-24 07:26:44',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id_pengguna' => 156,
                'username' => '23.05.049',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:32:14',
                'updated_at' => '2023-05-24 07:32:14',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id_pengguna' => 157,
                'username' => '23.05.050',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:32:43',
                'updated_at' => '2023-05-24 07:32:43',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id_pengguna' => 158,
                'username' => '23.05.051',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:33:20',
                'updated_at' => '2023-05-24 07:33:20',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id_pengguna' => 159,
                'username' => '23.05.052',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:33:39',
                'updated_at' => '2023-05-24 07:33:39',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id_pengguna' => 160,
                'username' => '23.05.053',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:34:51',
                'updated_at' => '2023-05-24 07:34:51',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id_pengguna' => 161,
                'username' => '23.05.054',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:35:17',
                'updated_at' => '2023-05-24 07:35:17',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id_pengguna' => 162,
                'username' => '23.05.045',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:36:45',
                'updated_at' => '2023-05-24 07:36:45',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id_pengguna' => 163,
                'username' => '23.05.046',
                'password' => bcrypt('0541'),
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:37:02',
                'updated_at' => '2023-05-24 07:37:02',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id_pengguna' => 171,
                'username' => 'Alfonsus',
                'password' => bcrypt('0541'),
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-06-02 13:56:09',
                'updated_at' => '2023-06-02 13:56:09',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}