<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PenggunaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pengguna')->delete();
        
        \DB::table('pengguna')->insert(array (
            0 => 
            array (
                'id_pengguna' => 1,
                'username' => 'alfonsus',
                'password' => '$2y$10$2HKoOs4jLqNnLEGjEQQpP.sd6HhOfpNXCzHHlqwzbMj1p9G4rDOTa',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-28 13:55:35',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id_pengguna' => 2,
                'username' => 'ucup_surucup',
                'password' => '$2y$10$ic2ra2GjqY8eeKekqlD0JuBzXezg0UoEVz4dWsEw/KwPyCbeCzCZ6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-06-05 18:14:38',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id_pengguna' => 3,
                'username' => 'udin_saprudin',
                'password' => '$2y$10$Kbv/pOXcOjiWAK55OtivQ.vnlXlhBTkMlt9g9mMGRWt0xKECuUy1u',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-21 17:09:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id_pengguna' => 4,
                'username' => 'faizah_nugraha',
                'password' => '$2y$10$gFQgNb1cE/.NONEGKRZAQ.lCQr1OlF2903TMcrBPuu7C6AUWBAteW',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id_pengguna' => 5,
                'username' => 'nadya',
                'password' => '$2y$10$2r9MbsElkWZOzYt6.2jxd.yUc6G3cYcwUJTc/VF7g/h8bfY7DTNhK',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id_pengguna' => 6,
                'username' => 'henry',
                'password' => '$2y$10$RzDMTwutndy9eTv8P17JleumPeOynf6xwKjMRtJAtyTXVpKX/xd6C',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:33',
                'updated_at' => '2023-04-02 00:54:33',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id_pengguna' => 7,
                'username' => 'Alfonsus',
                'password' => '$2y$10$4J.l.fJW/eLR7r4ZMr05oOdIdsC9vzNC3S1v.s88mBJCUi2qmPmwe',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id_pengguna' => 8,
                'username' => 'JK',
                'password' => '$2y$10$RgZ6laWcU4u2Vh1QBn8Q4OHaz1aSf2ylkoHMaUlIx9KNW1mCf0Zoa',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id_pengguna' => 9,
                'username' => 'Lisa',
                'password' => '$2y$10$t2MOhzUoLDtPengVfA06juv44GW8ss1RJFt3nsfqV.NFDu2RkqMCi',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id_pengguna' => 10,
                'username' => 'Hobby',
                'password' => '$2y$10$ouKTzb/uU0Zr4i7xoktXp.5AjEHGPU.oP.dDdtgXtbgxcEiUS1JHe',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id_pengguna' => 11,
                'username' => 'V',
                'password' => '$2y$10$KbjbFJGRF0i9/uIMqTLjded926Ml9vpqfTJj6n61vkKn5Atk.M.I.',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id_pengguna' => 12,
                'username' => 'Jenny',
                'password' => '$2y$10$R6NELKVnqu7hYhM.ky.DGOUKJYlqHzl8hocNRHGI/uZNhhvNVSHZG',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id_pengguna' => 13,
                'username' => 'Suga',
                'password' => '$2y$10$yY.lAAoX7lu1GDjFPJFJ3.4OA79Egf0JyMBDzsPOACkXzXy5iqU3a',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id_pengguna' => 14,
                'username' => 'Jin',
                'password' => '$2y$10$bWMpp4xS6RPWqJN6HEFXRunbOcj3UnlGUPDJEo12tjSZhH94rasJu',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id_pengguna' => 15,
                'username' => 'Jiso',
                'password' => '$2y$10$ZYBCqtyoeYClEgotmIBH.uSZHsLCQRId5Gw5fyh4r1P4qEa8gXkM.',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-05-16 01:18:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id_pengguna' => 16,
                'username' => 'Jimin',
                'password' => '$2y$10$9CoSioqMU1HHMCf4E83WvelpW/xNVjCaw53FWr0GrOKqJCAoMp1z6',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id_pengguna' => 17,
                'username' => 'Rose',
                'password' => '$2y$10$795iuTR4l6uNchMFkwaDmOdkCznxBPv6xP2y8iaP./evHLW0Z.DaC',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id_pengguna' => 18,
                'username' => 'Jessi',
                'password' => '$2y$10$V6CzbHqTgP6435Qg0oo6EumLNIyyYiwAakuOa3MPacauDv7wNwmim',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id_pengguna' => 19,
                'username' => 'admin',
                'password' => '$2y$10$knKC2eB7JkU9hcXLF8tPO.i6QKg1md1xaPOJ8fVAw0PVpqIwxGNQS',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:34',
                'updated_at' => '2023-04-02 00:54:34',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id_pengguna' => 20,
                'username' => 'admin_ganteng1',
                'password' => '$2y$10$wEa.XC67Ryn4SyFTsRUC/ee7b2cVA0xpgYLMuVck0.rCJDDo11Axa',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id_pengguna' => 21,
                'username' => 'mo_ganteng1',
                'password' => '$2y$10$m/TAt/yZWT6u3VWv2iV/ru6Ns1vJuulOBi.JaMfD7BFWJ9eCTjTo6',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-05-16 01:14:11',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id_pengguna' => 22,
                'username' => 'Yunita',
                'password' => '$2y$10$UAmx0bTPgrWIC1RrAtxJEu8ClJRilcHPaQHWnJH/Xrtlj3/Rc6fRG',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id_pengguna' => 23,
                'username' => 'Putri',
                'password' => '$2y$10$XsmnQX5C6dizU9WwGHIlwe9z2HsnVgJwYz6eJQadryMCK/L9PZCTK',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id_pengguna' => 24,
                'username' => 'Yuna',
                'password' => '$2y$10$fraDqt8adIi8UJBK/C7tMuIneEIkHTuKthID/Dbpr60QkfxbYD/iC',
                'role' => 'pegawai',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id_pengguna' => 25,
                'username' => 'Bambang',
                'password' => '$2y$10$4KZdLx/xwJc.ZbaDkNLlC.GBuYXnu99VwHgPN50zC0zfsX4PDo2BG',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id_pengguna' => 26,
                'username' => 'Tono',
                'password' => '$2y$10$lYKj8TetZt2zj8zoOTa5BeXQh/jwIZNWliM5rC.O8kbuZmexEEdVC',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id_pengguna' => 27,
                'username' => 'Adi',
                'password' => '$2y$10$eXNzcN383gxi9MTD2jYZaeYpTsFD7O3K1LQ9HxMJYcEgwpkGumm5m',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-02 00:54:35',
                'updated_at' => '2023-04-02 00:54:35',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id_pengguna' => 28,
                'username' => 'alfons',
                'password' => '$2y$10$10UJQ0P1oOOlRl/h6Nym5eOfZzDPlkj2bP6GROv5.x8TBW3vzXQqW',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:38:53',
                'updated_at' => '2023-04-14 20:38:53',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id_pengguna' => 29,
                'username' => 'alfons',
                'password' => '$2y$10$TV0hyOoE5gwxwhF4ZZkS9udxcLAV1vku2PHr4I21152hE9fsU6sre',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:39:32',
                'updated_at' => '2023-04-14 20:39:32',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id_pengguna' => 30,
                'username' => 'alfons',
                'password' => '$2y$10$4URBqPAxU8RYub.OJcj3IuyABSjKclAmTwbLLZflriynvQx4Z2/h2',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:45:15',
                'updated_at' => '2023-04-14 20:45:15',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id_pengguna' => 31,
                'username' => 'alfons',
                'password' => '$2y$10$O1OhVXGyvQ5EjJkRjhYd1eN0bW6t9tzsm8bctOESq1gc6PGw8Kez.',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:52:12',
                'updated_at' => '2023-04-14 20:52:12',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id_pengguna' => 32,
                'username' => 'alfons',
                'password' => '$2y$10$O9Qqn7b5stw7398OEfkCVOlsSCBw./9vel3lSHHjDQtTddYr/0GSC',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:52:55',
                'updated_at' => '2023-04-14 20:52:55',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id_pengguna' => 33,
                'username' => 'alfons',
                'password' => '$2y$10$C.VB7u6DdEXXDCV8f7Ol3uGtkNu4/puGaHoLyrfDHbo5uuooQWfM2',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:53:35',
                'updated_at' => '2023-04-14 20:53:35',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id_pengguna' => 34,
                'username' => 'alfons',
                'password' => '$2y$10$/KsoCNDtkWMAQDF8QIiwuOkVTHpMNBpRdusNkJR0S6slqHmuTF4ZS',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:54:28',
                'updated_at' => '2023-04-14 20:54:28',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id_pengguna' => 35,
                'username' => 'alfons',
                'password' => '$2y$10$7avB7bTUq9NeReivHJt72ORbtTlGHyAz9IhD9NRKGswe.m88YwlJi',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:54:46',
                'updated_at' => '2023-04-14 20:54:46',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id_pengguna' => 36,
                'username' => 'alfons',
                'password' => '$2y$10$zIxiU57EGOaI1by9BBy45O8P0EGLueCwBEejfuPfX5TcAojUgf9Qu',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:55:10',
                'updated_at' => '2023-04-14 20:55:10',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id_pengguna' => 37,
                'username' => 'alfons',
                'password' => '$2y$10$id4wJAIsC1hSlWCz7PtJXeyn4kYWS29yHcQZ280QcOA7Spd3DbR/C',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 20:55:40',
                'updated_at' => '2023-04-14 20:55:40',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id_pengguna' => 38,
                'username' => 'alfons',
                'password' => '$2y$10$aipOVGwlF2eNhVPYiUPWHu0l2JFo4TcO9Y/fF4qHSxOVO4S/UnXi2',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:01:58',
                'updated_at' => '2023-04-14 21:01:58',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id_pengguna' => 39,
                'username' => 'alfons',
                'password' => '$2y$10$rPc/LX5kslRL8Cp6USORKu5j2cwf65NcQzsvXFyHNjKAztAdcyH3m',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:03:13',
                'updated_at' => '2023-04-14 21:03:13',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id_pengguna' => 40,
                'username' => 'alfons',
                'password' => '$2y$10$bQvQ6rRftGD1HGrQSWUE3OFLjjd93IQuGk4sweKyIwrhGMuualYNG',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:06:27',
                'updated_at' => '2023-04-14 21:06:27',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id_pengguna' => 41,
                'username' => 'alfons',
                'password' => '$2y$10$6DOZrWSXjfKjYBhDzdfSBOPWTcFm7vLz670MfMX9JHd7N43.LAecu',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:14:55',
                'updated_at' => '2023-04-14 21:14:55',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id_pengguna' => 42,
                'username' => 'alfons',
                'password' => '$2y$10$fsY3jEO667mGxtbq8UjxleNldFyrule0ETIdgghF6DidJ6nlZnmIC',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:15:32',
                'updated_at' => '2023-04-14 21:15:32',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id_pengguna' => 43,
                'username' => 'alfons',
                'password' => '$2y$10$gfob5WfTkTD7JuuU0qlg0eFyIV5gS2kseMx33v8XLJrHDLXU/w8X.',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:16:27',
                'updated_at' => '2023-04-14 21:16:27',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id_pengguna' => 44,
                'username' => 'alfons',
                'password' => '$2y$10$VJPaCyFkvDl9SyFs7Ee.tu8jAF5FNukabCmXBxdMlfsBYICDzMYcW',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:18:00',
                'updated_at' => '2023-04-14 21:18:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id_pengguna' => 45,
                'username' => 'alfons',
                'password' => '$2y$10$BJduItfLaOFxuujgrm8QCe677M3iDvmkxtjOolxZuz9swDLdFECBG',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:19:37',
                'updated_at' => '2023-04-14 21:19:37',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id_pengguna' => 46,
                'username' => 'alfons',
                'password' => '$2y$10$QO2Lgv80tC2NdWxf.o6tHufpug5UIHLQXv0jHOwLB0h9rzlKlsVp6',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:20:55',
                'updated_at' => '2023-04-14 21:20:55',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id_pengguna' => 47,
                'username' => 'alfons',
                'password' => '$2y$10$/YacgDUw2WzrSTHp9ulegeTofXDilJBuymy86hu08Bb9niNzWBBJC',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:23:16',
                'updated_at' => '2023-04-14 21:23:16',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id_pengguna' => 48,
                'username' => 'alfons',
                'password' => '$2y$10$JPU8H2xHzlGaUwRxW4g0du7lo7tz7uJbJXOuCW0SisHmeO8WOM6S.',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:25:07',
                'updated_at' => '2023-04-14 21:25:07',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id_pengguna' => 49,
                'username' => 'alfons',
                'password' => '$2y$10$w6f5xi8t0lj3CGF69uSGFe2ZUlOwIQK.BH.h.I8EDjNqRYoj6jWoO',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:25:44',
                'updated_at' => '2023-04-14 21:25:44',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id_pengguna' => 50,
                'username' => 'alfons',
                'password' => '$2y$10$XoAnDNfKfbbqepKb5DVI/.M3GT4tpdUNKes0RldDwxrI0ZAjBMP8W',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:27:54',
                'updated_at' => '2023-04-14 21:27:54',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id_pengguna' => 51,
                'username' => 'alfons',
                'password' => '$2y$10$.AFbPJyVO9yvfNgzpxtrQ.oTBC4QIALYx0kP0sx/QU0PqXLspQR5m',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:28:10',
                'updated_at' => '2023-04-14 21:28:10',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id_pengguna' => 52,
                'username' => 'alfons',
                'password' => '$2y$10$5GpMbOf/J52uljoSwJMcz.1P50QYgl0lf6h5OOKTeDT7K9WrMIGZy',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:28:59',
                'updated_at' => '2023-04-14 21:28:59',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id_pengguna' => 53,
                'username' => 'alfons',
                'password' => '$2y$10$n8kyhaAMr98zDh72wYhpP.TPp.twt0L6HUyHpJosFfaNew5i3YsI6',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:30:03',
                'updated_at' => '2023-04-14 21:30:03',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id_pengguna' => 54,
                'username' => 'alfons',
                'password' => '$2y$10$SLzTXxMQB41GYG6d/Xr/cO80BcQA0v8447TzepUMkQvpJXgx8ZNja',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:32:35',
                'updated_at' => '2023-04-14 21:32:35',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id_pengguna' => 55,
                'username' => 'alfons',
                'password' => '$2y$10$3AqKacRpDCk7iOQX/w6XAOo5hZolftMz4URCN4Wqftsrjxj8D263y',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:32:47',
                'updated_at' => '2023-04-14 21:32:47',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id_pengguna' => 56,
                'username' => 'alfons',
                'password' => '$2y$10$FAdbzgY5cy9ZG.4afhmlM.N5vrALDN0XuSrZ.tU5IXFYz2G8GvtBC',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 21:56:10',
                'updated_at' => '2023-04-14 21:56:10',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id_pengguna' => 57,
                'username' => 'alfons',
                'password' => '$2y$10$vK1lY/LXuEcG7eUNL1QqXO8hNsI5aAGkVB2/RDmkUOCvnuwPuO/Iq',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:12:22',
                'updated_at' => '2023-04-14 22:12:22',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id_pengguna' => 58,
                'username' => 'alfons',
                'password' => '$2y$10$pV1VvBOfLAmfWYlF0gicgesyeISjBHltNnKV/SVu2PXum7ztKHrCS',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:16:46',
                'updated_at' => '2023-04-14 22:16:46',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id_pengguna' => 59,
                'username' => 'alfons',
                'password' => '$2y$10$1J/iHvmRcz1MMx0JA0XKZey/aKxR0.B9W09Koufw7l/Fa71kwWOxy',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:16:59',
                'updated_at' => '2023-04-14 22:16:59',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id_pengguna' => 60,
                'username' => 'alfons',
                'password' => '$2y$10$6PLLBkl0Cbn6rB0djl3GveGtaMWusmPDV42PdBAqvSPiDloseA8tq',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:17:27',
                'updated_at' => '2023-04-14 22:17:27',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id_pengguna' => 61,
                'username' => 'alfons',
                'password' => '$2y$10$AUpZCFosdwBSeIskMxBkcu85JZ05LkNstsWeDeJ1v8s/tcb58SP3C',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:40:31',
                'updated_at' => '2023-04-14 22:40:31',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id_pengguna' => 62,
                'username' => 'alfons',
                'password' => '$2y$10$qYOMOJI4kyCCA1rArOHC/.KmcwwFkOQePg7O.mBDtE7iqGE5KADgi',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:52:33',
                'updated_at' => '2023-04-14 22:52:33',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id_pengguna' => 63,
                'username' => 'alfons',
                'password' => '$2y$10$ZNbwHw1BuW8lFtyLw3UG9OhgqpfUOp7/TQY4ljoPTQirM5HU5BSeK',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:53:48',
                'updated_at' => '2023-04-14 22:53:48',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id_pengguna' => 64,
                'username' => 'alfons',
                'password' => '$2y$10$.uEkPxm.OCZyyrYIdOm0z.FTfDB7tHeLTbP.9eYCKE.svkaiBO2Ma',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:53:59',
                'updated_at' => '2023-04-14 22:53:59',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id_pengguna' => 65,
                'username' => 'alfons',
                'password' => '$2y$10$9lduTyKk57ppctXL9XVYM.G.VjNv4Wlt1ODBuBQVJ2fOM8O9yHZna',
                'role' => ' instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:56:17',
                'updated_at' => '2023-04-14 22:56:17',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id_pengguna' => 66,
                'username' => 'alfons',
                'password' => '$2y$10$87Tu32.qAwhekkcen6BQMuMrC55LggFHUks5lOZrZCeyiyx06sxvu',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-14 22:57:47',
                'updated_at' => '2023-04-14 22:57:47',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id_pengguna' => 67,
                'username' => '-',
                'password' => '$2y$10$2xLov.7ElJCY59qIgg0vzO1mIVqVzb9QVl3LIv9IESjhhT7yJ/JZK',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:31:07',
                'updated_at' => '2023-04-15 08:31:07',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id_pengguna' => 70,
                'username' => '-',
                'password' => '$2y$10$CFN0.7PN1.ipFSAtpEjLtuNQ1MYZHNHgKhzpBEzmWA7Ew/FrUhiM6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:32:44',
                'updated_at' => '2023-04-15 08:32:44',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id_pengguna' => 73,
                'username' => '-',
                'password' => '$2y$10$e3i95zyEo5umyblX1V3nZOwjaYmpbrleqL95o324Lv.XPfgataVru',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:35:31',
                'updated_at' => '2023-04-15 08:35:31',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id_pengguna' => 74,
                'username' => '-',
                'password' => '$2y$10$Azf8x.omUleiXnASWIW4nu49wpmIBW7v.f6Evu4bFbds9ThlF.KSG',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:35:54',
                'updated_at' => '2023-04-30 19:06:55',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id_pengguna' => 75,
                'username' => '-',
                'password' => '$2y$10$wwYQtZbrx9GgB98OxfJVZeq8nUOfEn54VY7kew5PAutJmrX/SY6we',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:37:18',
                'updated_at' => '2023-04-15 08:37:18',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id_pengguna' => 76,
                'username' => '-',
                'password' => '$2y$10$ndUeAUeI7pUcEFsj8gatVOA05BVgpj/QE2o94GiQTPUchpI2AVMTS',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:37:36',
                'updated_at' => '2023-04-15 08:37:36',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id_pengguna' => 91,
                'username' => '-',
                'password' => '$2y$10$o9EzDNp1aCbhptMR1duN6u09xC6mGWP3Bf2eJTTBr0nRsu3PKAgNm',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:50:36',
                'updated_at' => '2023-04-15 08:50:36',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id_pengguna' => 92,
                'username' => '-',
                'password' => '$2y$10$PZXmVwThlMl63304G5Jknex.XwVf5SBtYEIia1.r.vOd93EeyFvQ2',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:51:45',
                'updated_at' => '2023-04-15 08:51:45',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id_pengguna' => 93,
                'username' => '-',
                'password' => '$2y$10$OXZc5zKzhTEYXXLLa.la/O1xx.ud0JQgMguWbGe9t7SYuYaL7NvNC',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:52:35',
                'updated_at' => '2023-04-15 08:52:35',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id_pengguna' => 94,
                'username' => '-',
                'password' => '$2y$10$WWtbgaEY/zh2YbxW4sO/zOrKZ4ihzQ4YtAFcpJchSx0ZsJQXho.H6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:52:54',
                'updated_at' => '2023-04-15 08:52:54',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id_pengguna' => 97,
                'username' => '23.04.040',
                'password' => '$2y$10$vSlGYQflxIlD.Dmx0RAbse4ATxsEyYXCoLgdaqpvlXx/QwMxn1A5K',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:55:39',
                'updated_at' => '2023-04-15 08:55:39',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id_pengguna' => 98,
                'username' => '23.04.041',
                'password' => '$2y$10$vMs6mCGDY.ZL94AlTuB46uMfoGHsrO2I/CJIsGPWQIQE77FUEO8aW',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-15 08:56:24',
                'updated_at' => '2023-04-15 08:56:24',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id_pengguna' => 99,
                'username' => '23.04.021',
                'password' => '$2y$10$Inj9s4EalHD20skgBAaZ7e/66IsgrNqD/FNxdwD6fycb9RTSZEDei',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:03:56',
                'updated_at' => '2023-05-03 13:37:02',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id_pengguna' => 101,
                'username' => '23.04.023',
                'password' => '$2y$10$U//MamuWhmyvp5qgOECDUuHK3huxpAcmSPIsk0JAlCZq23nNaQKwS',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:35:25',
                'updated_at' => '2023-04-21 00:35:25',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id_pengguna' => 102,
                'username' => '23.04.024',
                'password' => '$2y$10$oHf2M3jOpwFQgm0ucmQbPOG2eTuwW.a4Jr856BMSfN1vojY7cCP0m',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:39:12',
                'updated_at' => '2023-04-21 00:39:12',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id_pengguna' => 103,
                'username' => '23.04.025',
                'password' => '$2y$10$wzwl/Yxgd0mXNQUOBKIz7.qUFz9BpXJdXnUuejUjhLsii38duRrMu',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:51:59',
                'updated_at' => '2023-04-21 00:51:59',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id_pengguna' => 104,
                'username' => '23.04.026',
                'password' => '$2y$10$njvk2hf1GHj.y2X2XX3QguK3EzfZ86ogZXyKeeWTCVF2Cf7mPJZbq',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:52:09',
                'updated_at' => '2023-04-21 00:52:09',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id_pengguna' => 105,
                'username' => '23.04.027',
                'password' => '$2y$10$yLrHuWIW3adAYBbvpf4Rf.d.AFaJO71YIO5vK/.gP5mZS74iPWVNS',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:52:19',
                'updated_at' => '2023-04-21 00:52:19',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id_pengguna' => 106,
                'username' => '23.04.028',
                'password' => '$2y$10$01XlxT7myTPaiQaNwxavRuS5KFAufYAIM22OWJ/hce.x/idP/Idwm',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:53:05',
                'updated_at' => '2023-04-21 00:53:05',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id_pengguna' => 107,
                'username' => '23.04.029',
                'password' => '$2y$10$UzonD1.w8W8U4ELpplw85OVZQxsGJwsVP6j3KX573WuubnFAfKBU6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 00:59:36',
                'updated_at' => '2023-04-21 00:59:36',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id_pengguna' => 109,
                'username' => '23.04.031',
                'password' => '$2y$10$lgkQQItryVEdJot2JDSMwewXNbWFPYUc3XUi8Flu3HbrqhZSIgo5O',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 01:08:35',
                'updated_at' => '2023-04-21 01:08:35',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id_pengguna' => 110,
                'username' => '23.04.032',
                'password' => '$2y$10$WwoJHmjNRTXx4L7PzRhi6e3h1tI7R8K2Xvn3Dc9J39VZwYuYAryY2',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 01:08:42',
                'updated_at' => '2023-04-21 01:08:42',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id_pengguna' => 111,
                'username' => '23.04.033',
                'password' => '$2y$10$Z2HIH/4c0sKwZglOs0QA5.FzZCXdShredVgY0sC7YpTsQOn3gnXWm',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 15:00:57',
                'updated_at' => '2023-04-21 15:00:57',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id_pengguna' => 113,
                'username' => '23.04.035',
                'password' => '$2y$10$UvjHsCguLclEPICYafsHkuqXL2LRJtlJYJjeX98jYW1Fr9RIQGNia',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-21 15:01:49',
                'updated_at' => '2023-04-21 15:01:49',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id_pengguna' => 118,
                'username' => '-',
                'password' => '$2y$10$abeZ1m2WBpKz4AeL1zDWBefv6f9kcsL7YkZ3wNBAZgn9HLO9PLuwK',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:23:21',
                'updated_at' => '2023-04-26 10:23:21',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id_pengguna' => 119,
                'username' => '-',
                'password' => '$2y$10$I.qsVxZNNO2Sv5JjKw4raObi6h/y6WWNgn4.Un6XNxH/p/QK9lluu',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:25:16',
                'updated_at' => '2023-04-26 10:25:16',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id_pengguna' => 120,
                'username' => '-',
                'password' => '$2y$10$CavJtXchpmUuLjSU4lYyzOrHcXnhWxaGB5Ok96Y50OFkNwY4JQgyq',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:26',
                'updated_at' => '2023-04-26 10:26:26',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id_pengguna' => 121,
                'username' => '-',
                'password' => '$2y$10$4vG2Wy6X3z7h0c0fbBxOuuq2dmfK3sZgy7FYFRoD0pFvqB0BJz.L2',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:47',
                'updated_at' => '2023-04-26 10:26:47',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id_pengguna' => 122,
                'username' => '-',
                'password' => '$2y$10$Yjs0N5TDitdEcy/CHDsVr.IiTvvQyO0ZJK7sNLirjMqKNP09bnvaW',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:26:48',
                'updated_at' => '2023-04-26 10:26:48',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id_pengguna' => 123,
                'username' => '-',
                'password' => '$2y$10$I0tvbmzvaqpHJNLfIOJ/dOxz0sVAZzkQa3ahs..ne7bqPi5V8E3m.',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:19',
                'updated_at' => '2023-04-26 10:27:19',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id_pengguna' => 124,
                'username' => '-',
                'password' => '$2y$10$.p5ARRADucBQT68lvY32veBwR.gIz38t/UmfYQVNynJs5AIzWD42i',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:20',
                'updated_at' => '2023-04-26 10:27:20',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id_pengguna' => 125,
                'username' => '-',
                'password' => '$2y$10$lND8dfEPImr4pB/ailqbzeWP7VECtgau1qHXLY3TaN8hnmrKrdthe',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-26 10:27:23',
                'updated_at' => '2023-04-26 10:27:23',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id_pengguna' => 130,
                'username' => '23.04.036',
                'password' => '$2y$10$9.tiayq5TwsIyl6H2e58tePCPcJoWXXezpm4jSaJPklA5wdV4FerG',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 10:44:58',
                'updated_at' => '2023-04-28 10:44:58',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id_pengguna' => 131,
                'username' => '23.04.037',
                'password' => '$2y$10$x6ZgFtMg85nw047USOGrw.f6rREGMCk6yWRRsnccuHmmJ4ctt.tPe',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 10:45:04',
                'updated_at' => '2023-05-03 13:34:13',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id_pengguna' => 138,
                'username' => 'Lisa Blacpink',
                'password' => '$2y$10$GZBuQG9zPDJRfWgP5YA.JeKURGPEzbhOW3kepXR4jTsmndjOVFi1q',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 13:46:06',
                'updated_at' => '2023-04-28 13:46:06',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id_pengguna' => 139,
                'username' => '23.04.038',
                'password' => '$2y$10$e3NDNjpBMerbCQnt4wpACeSdj9rwbangdI/gxwgohSKrSmCHjRpHa',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-28 13:50:17',
                'updated_at' => '2023-04-28 13:50:17',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id_pengguna' => 140,
                'username' => 'Jamet',
                'password' => '$2y$10$BmuDCKmPY/sPwF6mxW7dY.NBeCmoDbPlQPhm8NJA1hjslHx4zPwB6',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-04-29 21:36:55',
                'updated_at' => '2023-04-29 21:36:55',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id_pengguna' => 141,
                'username' => '23.04.039',
                'password' => '$2y$10$ApemIBaV0e5wJNqAse0Sw.FtSyjn.8R.qYL10PIOenxxZqQj6imjC',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-04-30 19:02:55',
                'updated_at' => '2023-04-30 19:02:55',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id_pengguna' => 143,
                'username' => '23.05.040',
                'password' => '$2y$10$wEJWxifkGc93gFHqQ1uwK.UJJX53yKEAkNVgwVJ/QjBPbViFqYAmu',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-05 13:32:38',
                'updated_at' => '2023-05-05 13:32:38',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id_pengguna' => 144,
                'username' => '23.05.041',
                'password' => '$2y$10$8UFJWnQjQQ4y6aW8hLnHIefyeFEJ3OaGDiC8UUbnfUEiNZxmYPkHG',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:02:22',
                'updated_at' => '2023-05-11 03:03:08',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id_pengguna' => 146,
                'username' => '23.05.042',
                'password' => '$2y$10$/5geKcarE13VwAD.oCzctuNUddAiKXGYaRBWqIy6EuUhfS0oUc1T.',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:09:32',
                'updated_at' => '2023-05-11 03:09:32',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id_pengguna' => 147,
                'username' => '23.05.043',
                'password' => '$2y$10$dj5MgegE4p4YS/duy6Hj0.wDyGA9SbUqwxUnVlGRDHTw/jM2rfJPm',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:13:59',
                'updated_at' => '2023-05-11 03:13:59',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id_pengguna' => 148,
                'username' => '-',
                'password' => '$2y$10$zpT3VrYkgoRpcV2AeX92ru97L5nULktI1SVfshrs9j.m2OuFInDIu',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:15:16',
                'updated_at' => '2023-05-11 03:15:16',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id_pengguna' => 149,
                'username' => '23.05.044',
                'password' => '$2y$10$IAEIeYfljQojzGAA8LxBG.ebMHSPPLp9O//LM4JeI7gGxAdW9B47S',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-11 03:15:59',
                'updated_at' => '2023-05-16 01:16:16',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id_pengguna' => 151,
                'username' => '23.05.045',
                'password' => '$2y$10$74x1Iu6aIJnuPk9Ac0PN6enjFjfmdsPn.hPPKazl6aZBYipgHES1m',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:21:51',
                'updated_at' => '2023-05-24 07:21:51',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id_pengguna' => 152,
                'username' => '23.05.045',
                'password' => '$2y$10$OAz.PLRueIiEx1hpR/hrD.49sBZkm8vHN/DpXx.Ki/TDaF2gc921y',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:23:14',
                'updated_at' => '2023-05-24 07:23:14',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id_pengguna' => 154,
                'username' => '23.05.047',
                'password' => '$2y$10$Yf576Vg/vOdAQZcM9oDb9eeV3hsbbKRz33UKzt8dLkNRq0u/Spreq',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:25:38',
                'updated_at' => '2023-05-24 07:25:38',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id_pengguna' => 155,
                'username' => '23.05.048',
                'password' => '$2y$10$URu350VFCWGAHIlNFuPqP.mc6twWDh/yHh09U1pNmUgW1xPT3PJ4S',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:26:44',
                'updated_at' => '2023-05-24 07:26:44',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id_pengguna' => 156,
                'username' => '23.05.049',
                'password' => '$2y$10$3KkhwJQVEOphvldYLkDsceqICABd6HhLrZi8y1UDEXNY7NSXwtiE6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:32:14',
                'updated_at' => '2023-05-24 07:32:14',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id_pengguna' => 157,
                'username' => '23.05.050',
                'password' => '$2y$10$nxzr8Eq7nEVG/kkFrFX4y.T0phcZ3.hYE4kst7KQ1hsaCb.C6snKe',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:32:43',
                'updated_at' => '2023-05-24 07:32:43',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id_pengguna' => 158,
                'username' => '23.05.051',
                'password' => '$2y$10$jPknVC.sNcOKQySPozqLUueutuFn1PrkkOmoGBTQS7llLhNxpGDJ6',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:33:20',
                'updated_at' => '2023-05-24 07:33:20',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id_pengguna' => 159,
                'username' => '23.05.052',
                'password' => '$2y$10$FNXy3pmnPDGzihRnqXfPiO2S3LtSBisjNKpg07flGeVrXiy6I6ruy',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:33:39',
                'updated_at' => '2023-05-24 07:33:39',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id_pengguna' => 160,
                'username' => '23.05.053',
                'password' => '$2y$10$rI8JisVcuWhaGHtMPkveq.882Z3eo.nCaRs1NVywu2hf9hjTnt1bC',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:34:51',
                'updated_at' => '2023-05-24 07:34:51',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id_pengguna' => 161,
                'username' => '23.05.054',
                'password' => '$2y$10$z.T6S/1ltpb37tgoQnPk7.fNU4EQhjTIzuK7fHeRQRMUsRR0AUkuS',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:35:17',
                'updated_at' => '2023-05-24 07:35:17',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id_pengguna' => 162,
                'username' => '23.05.045',
                'password' => '$2y$10$o0oTRwtulWI95k3k9AV/vuGlVNeFBkDra/2XPIfRfRqR/cnLrONty',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:36:45',
                'updated_at' => '2023-05-24 07:36:45',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id_pengguna' => 163,
                'username' => '23.05.046',
                'password' => '$2y$10$29joNfK6TMAMaQzDCUPJHuIVKESZJ6A67ry6d3qjU2fBAx3HaZk3u',
                'role' => 'member',
                'remember_token' => NULL,
                'created_at' => '2023-05-24 07:37:02',
                'updated_at' => '2023-05-24 07:37:02',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id_pengguna' => 171,
                'username' => 'Alfonsus',
                'password' => '$2y$10$fyEod2GiZkh9nnAksqZafeHNFelK24FlkwuBbDighW8ACReKkbZCK',
                'role' => 'instruktur',
                'remember_token' => NULL,
                'created_at' => '2023-06-02 13:56:09',
                'updated_at' => '2023-06-02 13:56:09',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}